# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddepartment_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDepartment(object):
    def setupUi(self, AddDepartment):
        AddDepartment.setObjectName("AddDepartment")
        AddDepartment.resize(337, 257)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddDepartment)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AddDepartment)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.name = QtWidgets.QLineEdit(AddDepartment)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.address_frame = QtWidgets.QFrame(AddDepartment)
        self.address_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.address_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.address_frame.setObjectName("address_frame")
        self.verticalLayout.addWidget(self.address_frame)
        self.submit_button = QtWidgets.QPushButton(AddDepartment)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)

        self.retranslateUi(AddDepartment)
        QtCore.QMetaObject.connectSlotsByName(AddDepartment)

    def retranslateUi(self, AddDepartment):
        _translate = QtCore.QCoreApplication.translate
        AddDepartment.setWindowTitle(_translate("AddDepartment", "Form"))
        self.label.setText(_translate("AddDepartment", "Название"))
        self.submit_button.setText(_translate("AddDepartment", "Добавить"))
