# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClientWidget(object):
    def setupUi(self, ClientWidget):
        ClientWidget.setObjectName("ClientWidget")
        ClientWidget.resize(381, 382)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(12)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ClientWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.compname = QtWidgets.QLineEdit(ClientWidget)
        self.compname.setObjectName("compname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.compname)
        self.label_2 = QtWidgets.QLabel(ClientWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.account = QtWidgets.QLineEdit(ClientWidget)
        self.account.setObjectName("account")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.account)
        self.label_4 = QtWidgets.QLabel(ClientWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.inn = QtWidgets.QLineEdit(ClientWidget)
        self.inn.setObjectName("inn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inn)
        self.label_5 = QtWidgets.QLabel(ClientWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ogrn = QtWidgets.QLineEdit(ClientWidget)
        self.ogrn.setObjectName("ogrn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ogrn)
        self.lphone = QtWidgets.QLabel(ClientWidget)
        self.lphone.setObjectName("lphone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lphone)
        self.phone = QtWidgets.QLineEdit(ClientWidget)
        self.phone.setAutoFillBackground(False)
        self.phone.setInputMask("")
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.phone)
        self.lemail = QtWidgets.QLabel(ClientWidget)
        self.lemail.setObjectName("lemail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lemail)
        self.email = QtWidgets.QLineEdit(ClientWidget)
        self.email.setAutoFillBackground(False)
        self.email.setObjectName("email")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.email)
        self.verticalLayout.addLayout(self.formLayout)
        self.address_frame = QtWidgets.QFrame(ClientWidget)
        self.address_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.address_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.address_frame.setObjectName("address_frame")
        self.verticalLayout.addWidget(self.address_frame)
        self.submit_button = QtWidgets.QPushButton(ClientWidget)
        self.submit_button.setObjectName("submit_button")
        self.verticalLayout.addWidget(self.submit_button)

        self.retranslateUi(ClientWidget)
        QtCore.QMetaObject.connectSlotsByName(ClientWidget)

    def retranslateUi(self, ClientWidget):
        _translate = QtCore.QCoreApplication.translate
        ClientWidget.setWindowTitle(_translate("ClientWidget", "Form"))
        self.label.setText(_translate("ClientWidget", "Название компании"))
        self.label_2.setText(_translate("ClientWidget", "Расчётный счёт"))
        self.label_4.setText(_translate("ClientWidget", "ИНН"))
        self.label_5.setText(_translate("ClientWidget", "ОГРН"))
        self.lphone.setText(_translate("ClientWidget", "Телефон"))
        self.lemail.setText(_translate("ClientWidget", "Email"))
        self.submit_button.setText(_translate("ClientWidget", "Ок"))
