# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginDialog(object):
    def setupUi(self, LoginDialog):
        LoginDialog.setObjectName("LoginDialog")
        LoginDialog.resize(358, 257)
        self.gridLayout = QtWidgets.QGridLayout(LoginDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(LoginDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(LoginDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(LoginDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.passwordBox = QtWidgets.QLineEdit(LoginDialog)
        self.passwordBox.setObjectName("passwordBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordBox)
        self.loginBox = QtWidgets.QLineEdit(LoginDialog)
        self.loginBox.setObjectName("loginBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginBox)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.submitButton = QtWidgets.QPushButton(LoginDialog)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout.addWidget(self.submitButton)
        self.lunregistred = QtWidgets.QLabel(LoginDialog)
        self.lunregistred.setStyleSheet("color:rgb(0, 85, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.lunregistred.setAlignment(QtCore.Qt.AlignCenter)
        self.lunregistred.setObjectName("lunregistred")
        self.horizontalLayout.addWidget(self.lunregistred)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)

        self.retranslateUi(LoginDialog)
        QtCore.QMetaObject.connectSlotsByName(LoginDialog)

    def retranslateUi(self, LoginDialog):
        _translate = QtCore.QCoreApplication.translate
        LoginDialog.setWindowTitle(_translate("LoginDialog", "Dialog"))
        self.label.setText(_translate("LoginDialog", "Вход"))
        self.label_2.setText(_translate("LoginDialog", "Логин:"))
        self.label_3.setText(_translate("LoginDialog", "Пароль:"))
        self.submitButton.setText(_translate("LoginDialog", "Ок"))
        self.lunregistred.setText(_translate("LoginDialog", "Зарегестироваться"))
