# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'membersview_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(787, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.position_box = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_box.sizePolicy().hasHeightForWidth())
        self.position_box.setSizePolicy(sizePolicy)
        self.position_box.setObjectName("position_box")
        self.horizontalLayout.addWidget(self.position_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_button = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_button.sizePolicy().hasHeightForWidth())
        self.add_button.setSizePolicy(sizePolicy)
        self.add_button.setObjectName("add_button")
        self.horizontalLayout.addWidget(self.add_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.MembersViewWidget = QtWidgets.QListWidget(Form)
        self.MembersViewWidget.setObjectName("MembersViewWidget")
        self.verticalLayout.addWidget(self.MembersViewWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.side_info = QtWidgets.QFrame(Form)
        self.side_info.setMinimumSize(QtCore.QSize(317, 0))
        self.side_info.setMaximumSize(QtCore.QSize(317, 16777215))
        self.side_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_info.setObjectName("side_info")
        self.horizontalLayout_2.addWidget(self.side_info)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Должность"))
        self.add_button.setText(_translate("Form", "Добавить"))
