# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projectcreate_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateProjectWidget(object):
    def setupUi(self, CreateProjectWidget):
        CreateProjectWidget.setObjectName("CreateProjectWidget")
        CreateProjectWidget.resize(434, 300)
        self.formLayout = QtWidgets.QFormLayout(CreateProjectWidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(CreateProjectWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.name = QtWidgets.QLineEdit(CreateProjectWidget)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(CreateProjectWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.start_date = QtWidgets.QDateEdit(CreateProjectWidget)
        self.start_date.setCalendarPopup(True)
        self.start_date.setDate(QtCore.QDate(2022, 1, 1))
        self.start_date.setObjectName("start_date")
        self.horizontalLayout.addWidget(self.start_date)
        self.label_3 = QtWidgets.QLabel(CreateProjectWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.end_date = QtWidgets.QDateEdit(CreateProjectWidget)
        self.end_date.setCalendarPopup(True)
        self.end_date.setDate(QtCore.QDate(2023, 1, 1))
        self.end_date.setObjectName("end_date")
        self.horizontalLayout.addWidget(self.end_date)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.label_4 = QtWidgets.QLabel(CreateProjectWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.contract_add = QtWidgets.QPushButton(CreateProjectWidget)
        self.contract_add.setObjectName("contract_add")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.contract_add)
        self.label_5 = QtWidgets.QLabel(CreateProjectWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.submitButton = QtWidgets.QPushButton(CreateProjectWidget)
        self.submitButton.setObjectName("submitButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.submitButton)
        self.description = QtWidgets.QPlainTextEdit(CreateProjectWidget)
        self.description.setObjectName("description")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.description)

        self.retranslateUi(CreateProjectWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateProjectWidget)

    def retranslateUi(self, CreateProjectWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateProjectWidget.setWindowTitle(_translate("CreateProjectWidget", "Form"))
        self.label.setText(_translate("CreateProjectWidget", "Название"))
        self.label_2.setText(_translate("CreateProjectWidget", "Дата начала"))
        self.label_3.setText(_translate("CreateProjectWidget", "Дата конца"))
        self.label_4.setText(_translate("CreateProjectWidget", "Контракт"))
        self.contract_add.setText(_translate("CreateProjectWidget", "Добавить контракт"))
        self.label_5.setText(_translate("CreateProjectWidget", "Описание"))
        self.submitButton.setText(_translate("CreateProjectWidget", "Ок"))
