# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SumProjectWidget(object):
    def setupUi(self, SumProjectWidget):
        SumProjectWidget.setObjectName("SumProjectWidget")
        SumProjectWidget.resize(1040, 728)
        self.gridLayout = QtWidgets.QGridLayout(SumProjectWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SumProjectWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.description_editor = QtWidgets.QPlainTextEdit(SumProjectWidget)
        self.description_editor.setEnabled(True)
        self.description_editor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.description_editor.setFrameShadow(QtWidgets.QFrame.Plain)
        self.description_editor.setReadOnly(False)
        self.description_editor.setOverwriteMode(False)
        self.description_editor.setBackgroundVisible(True)
        self.description_editor.setObjectName("description_editor")
        self.verticalLayout.addWidget(self.description_editor)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.members_group = QtWidgets.QGroupBox(SumProjectWidget)
        self.members_group.setMinimumSize(QtCore.QSize(0, 250))
        self.members_group.setObjectName("members_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.members_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.members_scroll = QtWidgets.QScrollArea(self.members_group)
        self.members_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.members_scroll.setWidgetResizable(True)
        self.members_scroll.setObjectName("members_scroll")
        self.members_content = QtWidgets.QWidget()
        self.members_content.setGeometry(QtCore.QRect(0, 0, 327, 290))
        self.members_content.setObjectName("members_content")
        self.members_scroll.setWidget(self.members_content)
        self.verticalLayout_2.addWidget(self.members_scroll)
        self.member_button = QtWidgets.QPushButton(self.members_group)
        self.member_button.setObjectName("member_button")
        self.verticalLayout_2.addWidget(self.member_button)
        self.gridLayout.addWidget(self.members_group, 1, 0, 1, 1)
        self.tasks_group = QtWidgets.QGroupBox(SumProjectWidget)
        self.tasks_group.setMinimumSize(QtCore.QSize(0, 250))
        self.tasks_group.setFlat(False)
        self.tasks_group.setCheckable(False)
        self.tasks_group.setObjectName("tasks_group")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tasks_group)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tasks_scroll = QtWidgets.QScrollArea(self.tasks_group)
        self.tasks_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tasks_scroll.setWidgetResizable(True)
        self.tasks_scroll.setObjectName("tasks_scroll")
        self.tasks_content = QtWidgets.QWidget()
        self.tasks_content.setGeometry(QtCore.QRect(0, 0, 326, 290))
        self.tasks_content.setObjectName("tasks_content")
        self.tasks_scroll.setWidget(self.tasks_content)
        self.verticalLayout_3.addWidget(self.tasks_scroll)
        self.tasks_button = QtWidgets.QPushButton(self.tasks_group)
        self.tasks_button.setObjectName("tasks_button")
        self.verticalLayout_3.addWidget(self.tasks_button)
        self.gridLayout.addWidget(self.tasks_group, 1, 1, 1, 1)
        self.side_info = QtWidgets.QFrame(SumProjectWidget)
        self.side_info.setMinimumSize(QtCore.QSize(317, 0))
        self.side_info.setMaximumSize(QtCore.QSize(317, 16777215))
        self.side_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_info.setObjectName("side_info")
        self.gridLayout.addWidget(self.side_info, 0, 2, 2, 1)

        self.retranslateUi(SumProjectWidget)
        QtCore.QMetaObject.connectSlotsByName(SumProjectWidget)

    def retranslateUi(self, SumProjectWidget):
        _translate = QtCore.QCoreApplication.translate
        SumProjectWidget.setWindowTitle(_translate("SumProjectWidget", "Form"))
        self.label.setText(_translate("SumProjectWidget", "Описание"))
        self.members_group.setTitle(_translate("SumProjectWidget", "Участники"))
        self.member_button.setText(_translate("SumProjectWidget", "Добавить участника"))
        self.tasks_group.setTitle(_translate("SumProjectWidget", "Задачи"))
        self.tasks_button.setText(_translate("SumProjectWidget", "Добавить задачу"))
