# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterDialog(object):
    def setupUi(self, RegisterDialog):
        RegisterDialog.setObjectName("RegisterDialog")
        RegisterDialog.resize(383, 299)
        self.gridLayout_2 = QtWidgets.QGridLayout(RegisterDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(RegisterDialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(RegisterDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.loginBox = QtWidgets.QLineEdit(RegisterDialog)
        self.loginBox.setObjectName("loginBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginBox)
        self.label_3 = QtWidgets.QLabel(RegisterDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.passwordBox = QtWidgets.QLineEdit(RegisterDialog)
        self.passwordBox.setObjectName("passwordBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.passwordBox)
        self.label_4 = QtWidgets.QLabel(RegisterDialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.checkpasswordBox = QtWidgets.QLineEdit(RegisterDialog)
        self.checkpasswordBox.setObjectName("checkpasswordBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkpasswordBox)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.submitButton = QtWidgets.QPushButton(RegisterDialog)
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout.addWidget(self.submitButton)
        self.lenter = QtWidgets.QLabel(RegisterDialog)
        self.lenter.setStyleSheet("color:rgb(0, 85, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;")
        self.lenter.setAlignment(QtCore.Qt.AlignCenter)
        self.lenter.setObjectName("lenter")
        self.horizontalLayout.addWidget(self.lenter)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(RegisterDialog)
        QtCore.QMetaObject.connectSlotsByName(RegisterDialog)

    def retranslateUi(self, RegisterDialog):
        _translate = QtCore.QCoreApplication.translate
        RegisterDialog.setWindowTitle(_translate("RegisterDialog", "Dialog"))
        self.label.setText(_translate("RegisterDialog", "Регистрация"))
        self.label_2.setText(_translate("RegisterDialog", "Логин:"))
        self.label_3.setText(_translate("RegisterDialog", "Пароль:"))
        self.label_4.setText(_translate("RegisterDialog", "Повтроите пароль:"))
        self.submitButton.setText(_translate("RegisterDialog", "Ок"))
        self.lenter.setText(_translate("RegisterDialog", "Войти"))
