# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'requirement_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReqWidget(object):
    def setupUi(self, ReqWidget):
        ReqWidget.setObjectName("ReqWidget")
        ReqWidget.resize(311, 170)
        self.formLayout = QtWidgets.QFormLayout(ReqWidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ReqWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.gost = QtWidgets.QLineEdit(ReqWidget)
        self.gost.setObjectName("gost")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gost)
        self.label_2 = QtWidgets.QLabel(ReqWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.content = QtWidgets.QTextEdit(ReqWidget)
        self.content.setObjectName("content")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.content)
        self.remreq_button = QtWidgets.QPushButton(ReqWidget)
        self.remreq_button.setObjectName("remreq_button")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.remreq_button)

        self.retranslateUi(ReqWidget)
        QtCore.QMetaObject.connectSlotsByName(ReqWidget)

    def retranslateUi(self, ReqWidget):
        _translate = QtCore.QCoreApplication.translate
        ReqWidget.setWindowTitle(_translate("ReqWidget", "Form"))
        self.label.setText(_translate("ReqWidget", "Гост"))
        self.label_2.setText(_translate("ReqWidget", "Содержание"))
        self.remreq_button.setText(_translate("ReqWidget", "Убрать требование"))
