# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'side_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SideClientWidget(object):
    def setupUi(self, SideClientWidget):
        SideClientWidget.setObjectName("SideClientWidget")
        SideClientWidget.resize(311, 440)
        self.formLayout = QtWidgets.QFormLayout(SideClientWidget)
        self.formLayout.setVerticalSpacing(18)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(SideClientWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.compname = QtWidgets.QLineEdit(SideClientWidget)
        self.compname.setObjectName("compname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.compname)
        self.label_2 = QtWidgets.QLabel(SideClientWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.account = QtWidgets.QLineEdit(SideClientWidget)
        self.account.setObjectName("account")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.account)
        self.label_4 = QtWidgets.QLabel(SideClientWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.inn = QtWidgets.QLineEdit(SideClientWidget)
        self.inn.setObjectName("inn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.inn)
        self.label_5 = QtWidgets.QLabel(SideClientWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.ogrn = QtWidgets.QLineEdit(SideClientWidget)
        self.ogrn.setObjectName("ogrn")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ogrn)
        self.lphone = QtWidgets.QLabel(SideClientWidget)
        self.lphone.setObjectName("lphone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lphone)
        self.phone = QtWidgets.QLineEdit(SideClientWidget)
        self.phone.setAutoFillBackground(False)
        self.phone.setInputMask("")
        self.phone.setText("")
        self.phone.setObjectName("phone")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.phone)
        self.lemail = QtWidgets.QLabel(SideClientWidget)
        self.lemail.setObjectName("lemail")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lemail)
        self.email = QtWidgets.QLineEdit(SideClientWidget)
        self.email.setAutoFillBackground(False)
        self.email.setObjectName("email")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.email)
        self.label_6 = QtWidgets.QLabel(SideClientWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.contract_number = QtWidgets.QLineEdit(SideClientWidget)
        self.contract_number.setObjectName("contract_number")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.contract_number)
        self.label_7 = QtWidgets.QLabel(SideClientWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cost_edit = QtWidgets.QLineEdit(SideClientWidget)
        self.cost_edit.setObjectName("cost_edit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cost_edit)
        self.label_3 = QtWidgets.QLabel(SideClientWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sign_date = QtWidgets.QDateEdit(SideClientWidget)
        self.sign_date.setCalendarPopup(True)
        self.sign_date.setDate(QtCore.QDate(2022, 1, 1))
        self.sign_date.setObjectName("sign_date")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.sign_date)

        self.retranslateUi(SideClientWidget)
        QtCore.QMetaObject.connectSlotsByName(SideClientWidget)

    def retranslateUi(self, SideClientWidget):
        _translate = QtCore.QCoreApplication.translate
        SideClientWidget.setWindowTitle(_translate("SideClientWidget", "Form"))
        self.label.setText(_translate("SideClientWidget", "Название компании"))
        self.label_2.setText(_translate("SideClientWidget", "Расчётный счёт"))
        self.label_4.setText(_translate("SideClientWidget", "ИНН"))
        self.label_5.setText(_translate("SideClientWidget", "ОГРН"))
        self.lphone.setText(_translate("SideClientWidget", "Телефон"))
        self.lemail.setText(_translate("SideClientWidget", "Email"))
        self.label_6.setText(_translate("SideClientWidget", "Номер контракта"))
        self.label_7.setText(_translate("SideClientWidget", "Стоимость"))
        self.label_3.setText(_translate("SideClientWidget", "Дата подписания"))
