# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskWidget(object):
    def setupUi(self, TaskWidget):
        TaskWidget.setObjectName("TaskWidget")
        TaskWidget.resize(722, 71)
        self.gridLayout = QtWidgets.QGridLayout(TaskWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.task_name = QtWidgets.QLabel(TaskWidget)
        self.task_name.setObjectName("task_name")
        self.gridLayout.addWidget(self.task_name, 0, 0, 1, 3)
        self.status_box = QtWidgets.QComboBox(TaskWidget)
        self.status_box.setObjectName("status_box")
        self.gridLayout.addWidget(self.status_box, 1, 1, 1, 1)
        self.priority_box = QtWidgets.QComboBox(TaskWidget)
        self.priority_box.setObjectName("priority_box")
        self.gridLayout.addWidget(self.priority_box, 1, 0, 1, 1)
        self.time = QtWidgets.QLabel(TaskWidget)
        self.time.setObjectName("time")
        self.gridLayout.addWidget(self.time, 1, 3, 1, 1)
        self.executor = QtWidgets.QLabel(TaskWidget)
        self.executor.setObjectName("executor")
        self.gridLayout.addWidget(self.executor, 1, 2, 1, 1)

        self.retranslateUi(TaskWidget)
        QtCore.QMetaObject.connectSlotsByName(TaskWidget)

    def retranslateUi(self, TaskWidget):
        _translate = QtCore.QCoreApplication.translate
        TaskWidget.setWindowTitle(_translate("TaskWidget", "Form"))
        self.task_name.setText(_translate("TaskWidget", "TextLabel"))
        self.time.setText(_translate("TaskWidget", "TextLabel"))
        self.executor.setText(_translate("TaskWidget", "TextLabel"))
