# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'techtask_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TeckTaskDialog(object):
    def setupUi(self, TeckTaskDialog):
        TeckTaskDialog.setObjectName("TeckTaskDialog")
        TeckTaskDialog.resize(677, 577)
        self.gridLayout = QtWidgets.QGridLayout(TeckTaskDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lname = QtWidgets.QLabel(TeckTaskDialog)
        self.lname.setObjectName("lname")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lname)
        self.num_edit = QtWidgets.QLineEdit(TeckTaskDialog)
        self.num_edit.setAutoFillBackground(False)
        self.num_edit.setObjectName("num_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.num_edit)
        self.label = QtWidgets.QLabel(TeckTaskDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.purpose_edit = QtWidgets.QTextEdit(TeckTaskDialog)
        self.purpose_edit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.purpose_edit.setObjectName("purpose_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.purpose_edit)
        self.label_5 = QtWidgets.QLabel(TeckTaskDialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.description_edit = QtWidgets.QTextEdit(TeckTaskDialog)
        self.description_edit.setObjectName("description_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.description_edit)
        self.label_2 = QtWidgets.QLabel(TeckTaskDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.workorder_edit = QtWidgets.QTextEdit(TeckTaskDialog)
        self.workorder_edit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.workorder_edit.setObjectName("workorder_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.workorder_edit)
        self.label_3 = QtWidgets.QLabel(TeckTaskDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.control_edit = QtWidgets.QTextEdit(TeckTaskDialog)
        self.control_edit.setMaximumSize(QtCore.QSize(16777215, 150))
        self.control_edit.setObjectName("control_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.control_edit)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(TeckTaskDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.req_scroll = QtWidgets.QScrollArea(TeckTaskDialog)
        self.req_scroll.setWidgetResizable(True)
        self.req_scroll.setObjectName("req_scroll")
        self.req_area = QtWidgets.QWidget()
        self.req_area.setGeometry(QtCore.QRect(0, 0, 276, 472))
        self.req_area.setObjectName("req_area")
        self.req_scroll.setWidget(self.req_area)
        self.verticalLayout.addWidget(self.req_scroll)
        self.add_req = QtWidgets.QPushButton(TeckTaskDialog)
        self.add_req.setObjectName("add_req")
        self.verticalLayout.addWidget(self.add_req)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.submitButton = QtWidgets.QPushButton(TeckTaskDialog)
        self.submitButton.setObjectName("submitButton")
        self.gridLayout.addWidget(self.submitButton, 1, 1, 1, 1)

        self.retranslateUi(TeckTaskDialog)
        QtCore.QMetaObject.connectSlotsByName(TeckTaskDialog)

    def retranslateUi(self, TeckTaskDialog):
        _translate = QtCore.QCoreApplication.translate
        TeckTaskDialog.setWindowTitle(_translate("TeckTaskDialog", "Dialog"))
        self.lname.setText(_translate("TeckTaskDialog", "Номер"))
        self.label.setText(_translate("TeckTaskDialog", "Цель"))
        self.label_5.setText(_translate("TeckTaskDialog", "Описание"))
        self.label_2.setText(_translate("TeckTaskDialog", "Порядок работ"))
        self.label_3.setText(_translate("TeckTaskDialog", "Процедуры контроля"))
        self.label_4.setText(_translate("TeckTaskDialog", "Требования"))
        self.add_req.setText(_translate("TeckTaskDialog", "Добавить требование"))
        self.submitButton.setText(_translate("TeckTaskDialog", "Добавить"))
