# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome_projectslist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProjectListWidget(object):
    def setupUi(self, ProjectListWidget):
        ProjectListWidget.setObjectName("ProjectListWidget")
        ProjectListWidget.resize(333, 435)
        self.verticalLayout = QtWidgets.QVBoxLayout(ProjectListWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ProjectListWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.projects_list = QtWidgets.QListWidget(ProjectListWidget)
        self.projects_list.setObjectName("projects_list")
        self.verticalLayout.addWidget(self.projects_list)
        self.add_button = QtWidgets.QPushButton(ProjectListWidget)
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)

        self.retranslateUi(ProjectListWidget)
        QtCore.QMetaObject.connectSlotsByName(ProjectListWidget)

    def retranslateUi(self, ProjectListWidget):
        _translate = QtCore.QCoreApplication.translate
        ProjectListWidget.setWindowTitle(_translate("ProjectListWidget", "Form"))
        self.label.setText(_translate("ProjectListWidget", "Проекты"))
        self.add_button.setText(_translate("ProjectListWidget", "Добавить"))
