"""add project desc, feature status, priority

Revision ID: 0b233d8d51be
Revises: 09de1aff0b45
Create Date: 2022-06-15 16:35:26.989512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from db.models import Priority, Status


# revision identifiers, used by Alembic.
revision = '0b233d8d51be'
down_revision = '09de1aff0b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('geography_columns',
    # sa.Column('f_table_catalog', sa.String(), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geography_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.Text(), nullable=True)
    # )
    # op.create_table('geometry_columns',
    # sa.Column('f_table_catalog', sa.String(length=256), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geometry_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.String(length=30), nullable=True)
    # )
    status_type = postgresql.ENUM(Status, name='status')
    priority_type = postgresql.ENUM(Priority, name='priority')
    op.add_column('feature', sa.Column('status', status_type, server_default=sa.text("'открыта'::status"), nullable=False))
    op.add_column('feature', sa.Column('priority', priority_type, nullable=True))
    op.add_column('project', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'description')
    op.drop_column('feature', 'priority')
    op.drop_column('feature', 'status')
    op.drop_table('geometry_columns')
    op.drop_table('geography_columns')
    # ### end Alembic commands ###
