"""fix male female

Revision ID: 10a177147967
Revises: 25890953288f
Create Date: 2022-06-16 03:49:29.580217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

from db.models import Sex

revision = '10a177147967'
down_revision = '25890953288f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('geography_columns',
    # sa.Column('f_table_catalog', sa.String(), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geography_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.Text(), nullable=True)
    # )
    # op.create_table('geometry_columns',
    # sa.Column('f_table_catalog', sa.String(length=256), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geometry_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.String(length=30), nullable=True)
    # )
    sex_type = postgresql.ENUM(Sex, name='priority')
    sex_type.create(op.get_bind(), checkfirst=True)
    op.alter_column('employee', 'sex', existing_type=sex_type)
    op.alter_column('client', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('client_address_fkey', 'client', type_='foreignkey')
    op.drop_column('client', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_address_fkey', 'client', 'address', ['address'], ['id'])
    op.alter_column('client', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('geometry_columns')
    op.drop_table('geography_columns')
    # ### end Alembic commands ###
