"""add techtask number, client name

Revision ID: 25890953288f
Revises: 0b233d8d51be
Create Date: 2022-06-16 00:48:26.170464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25890953288f'
down_revision = '0b233d8d51be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('geography_columns',
    # sa.Column('f_table_catalog', sa.String(), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geography_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.Text(), nullable=True)
    # )
    # op.create_table('geometry_columns',
    # sa.Column('f_table_catalog', sa.String(length=256), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geometry_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.String(length=30), nullable=True)
    # )
    op.add_column('client', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('client', sa.Column('address', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client', 'address', ['address'], ['id'])
    op.add_column('techtask', sa.Column('number', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('techtask', 'number')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'address')
    op.drop_column('client', 'name')
    op.drop_table('geometry_columns')
    op.drop_table('geography_columns')
    # ### end Alembic commands ###
