"""initial

Revision ID: 3e98a717b76c
Revises: 
Create Date: 2022-06-13 09:42:58.734993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e98a717b76c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geography_columns',
    sa.Column('f_table_catalog', sa.String(), nullable=True),
    sa.Column('f_table_schema', sa.String(), nullable=True),
    sa.Column('f_table_name', sa.String(), nullable=True),
    sa.Column('f_geography_column', sa.String(), nullable=True),
    sa.Column('coord_dimension', sa.Integer(), nullable=True),
    sa.Column('srid', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True)
    )
    op.create_table('geometry_columns',
    sa.Column('f_table_catalog', sa.String(length=256), nullable=True),
    sa.Column('f_table_schema', sa.String(), nullable=True),
    sa.Column('f_table_name', sa.String(), nullable=True),
    sa.Column('f_geometry_column', sa.String(), nullable=True),
    sa.Column('coord_dimension', sa.Integer(), nullable=True),
    sa.Column('srid', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True)
    )
    op.drop_constraint('client_address_fkey', 'client', type_='foreignkey')
    op.drop_column('client', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_address_fkey', 'client', 'address', ['address_id'], ['id'])
    op.drop_table('geometry_columns')
    op.drop_table('geography_columns')
    # ### end Alembic commands ###
