"""add name to feature task mistake

Revision ID: 6bc51568b230
Revises: 10a177147967
Create Date: 2022-06-16 09:39:32.610404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc51568b230'
down_revision = '10a177147967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('geography_columns',
    # sa.Column('f_table_catalog', sa.String(), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geography_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.Text(), nullable=True)
    # )
    # op.create_table('geometry_columns',
    # sa.Column('f_table_catalog', sa.String(length=256), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geometry_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.String(length=30), nullable=True)
    # )
    op.add_column('feature', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('mistake', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('task', sa.Column('name', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'name')
    op.drop_column('mistake', 'name')
    op.drop_column('feature', 'name')
    op.drop_table('geometry_columns')
    op.drop_table('geography_columns')
    # ### end Alembic commands ###
