"""add priority and projecthead

Revision ID: e35e2c57a6e7
Revises: 3e98a717b76c
Create Date: 2022-06-13 12:11:11.432564

"""
from alembic import op
import sqlalchemy as sa
from db.models import Priority
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.

revision = 'e35e2c57a6e7'
down_revision = '3e98a717b76c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('geography_columns',
    # sa.Column('f_table_catalog', sa.String(), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geography_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.Text(), nullable=True)
    # )
    # op.create_table('geometry_columns',
    # sa.Column('f_table_catalog', sa.String(length=256), nullable=True),
    # sa.Column('f_table_schema', sa.String(), nullable=True),
    # sa.Column('f_table_name', sa.String(), nullable=True),
    # sa.Column('f_geometry_column', sa.String(), nullable=True),
    # sa.Column('coord_dimension', sa.Integer(), nullable=True),
    # sa.Column('srid', sa.Integer(), nullable=True),
    # sa.Column('type', sa.String(length=30), nullable=True)
    # )
    op.drop_constraint('client_address_fkey', 'client', type_='foreignkey')
    op.drop_column('client', 'address_id')
    priority_type = postgresql.ENUM(Priority, name='priority')
    priority_type.create(op.get_bind(), checkfirst=True)
    op.add_column('mistake', sa.Column('priority', priority_type, nullable=True))
    op.add_column('project', sa.Column('head_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'employee', ['head_id'], ['id'])
    op.add_column('task', sa.Column('priority', priority_type, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    priority_type = postgresql.ENUM(Priority, name='priority')
    priority_type.delete(op.get_bind())
    op.drop_column('task', 'priority')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'head_id')
    op.drop_column('mistake', 'priority')
    op.add_column('client', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('client_address_fkey', 'client', 'address', ['address_id'], ['id'])
    # op.drop_table('geometry_columns')
    # op.drop_table('geography_columns')
    # ### end Alembic commands ###
